"""LaTeX source export: the same blocks as the PDF, as a standalone .tex file
the user can open in Overleaf and keep editing.

Real LaTeX resumes have well-known ATS failure modes; this output avoids each:
- ligatures ("fi", "ffi") extract as single odd glyphs -> disabled;
- missing ToUnicode maps make text unextractable -> \\pdfgentounicode=1
  (pdfLaTeX) or fontspec's native Unicode (LuaLaTeX/XeLaTeX);
- tightly spaced faces extract as "DataAnalyst" because TeX spaces are gaps,
  not characters -> \\pdfinterwordspaceon writes real spaces;
- tabular-based entry headers can be read cell by cell -> plain \\hfill rows;
- fancyhdr headers/footers get skipped by parsers -> \\pagestyle{empty},
  contact details in the body.

Compiles with pdfLaTeX (Overleaf's default). If the resume contains
characters pdfLaTeX can't typeset, the file asks for LuaLaTeX instead via the
"% !TEX program" magic comment.
"""

import re

from app.builder.layout import Block, build_blocks
from app.builder.templates import TEMPLATES, Style, resolve_style
from app.schemas.resume import ResumeDocument

_ESCAPES = {
    "\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
    "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
    "<": r"\textless{}", ">": r"\textgreater{}", "|": r"\textbar{}",
}
_ESCAPE_RE = re.compile("|".join(re.escape(ch) for ch in _ESCAPES))

# Typeset by pdfLaTeX's utf8 + T1 setup without extra packages.
_PDFTEX_SAFE = re.compile("^[\u0000-ɏ‐-‧‰-›€™]*$")

# Latin Modern has no Greek, Cyrillic or other scripts; under LuaLaTeX those
# characters fall back to DejaVu (part of TeX Live) instead of vanishing.
_LUA_FALLBACK = (
    r"\ifLuaTeX\directlua{luaotfload.add_fallback('resumefallback',"
    r"{'DejaVu Serif:mode=harf;','DejaVu Sans:mode=harf;'})}"
    r"\setmainfont{Latin Modern %s}[RawFeature={fallback=resumefallback}]"
    r"\else\setmainfont{Latin Modern %s}\fi"
)
_FONT_SETUP = {
    # (pdfLaTeX, LuaLaTeX/XeLaTeX)
    "lmroman": (r"\usepackage{lmodern}", _LUA_FALLBACK % ("Roman", "Roman")),
    "lmsans": (r"\usepackage{lmodern}" "\n" r"  \renewcommand{\familydefault}{\sfdefault}",
               _LUA_FALLBACK % ("Sans", "Sans")),
    "sourcesans": (r"\usepackage[default]{sourcesanspro}", r"\usepackage[default]{sourcesanspro}"),
}

PT = 25.4 / 72


def escape(text: str) -> str:
    return _ESCAPE_RE.sub(lambda m: _ESCAPES[m.group(0)], text)


def _url_arg(url: str) -> str:
    return re.sub(r"[{}\\\s]", "", url).replace("%", r"\%").replace("#", r"\#")


def _contact_item(part: str) -> str:
    if re.fullmatch(r"[^@\s]+@[^@\s]+\.[^@\s]+", part):
        return rf"\href{{mailto:{_url_arg(part)}}}{{{escape(part)}}}"
    if re.fullmatch(r"(https?://)?[\w.-]+\.[a-z]{2,}(/\S*)?", part, re.IGNORECASE):
        target = part if part.lower().startswith("http") else f"https://{part}"
        return rf"\href{{{_url_arg(target)}}}{{{escape(part)}}}"
    return escape(part)


def _size(pt: float, leading: float) -> str:
    # The trailing space ends the control word; TeX discards it.
    return rf"\fontsize{{{pt:.2f}pt}}{{{pt * leading:.2f}pt}}\selectfont "


def _hex(rgb: tuple[int, int, int]) -> str:
    return "{:02X}{:02X}{:02X}".format(*rgb)


def _section_macro(style: Style) -> str:
    size = _size(style.font_size * 1.15, 1.25)
    case = r"\scshape" if style.heading_case == "smallcaps" else ""
    title = rf"{{{size}\bfseries{case}\color{{accent}}#1}}"
    before = rf"\vspace{{{style.font_size * style.line_height * PT * 0.75:.2f}mm}}"
    centered = style.heading_align == "center"
    if style.heading_style == "rule":
        body = (rf"{{\centering {title}\par}}" if centered else rf"{title}\par") + (
            r"\vspace{0.3mm}{\color{rulecolor}\hrule height 0.3mm}\vspace{1.5mm}"
        )
    elif style.heading_style == "line":
        fill = r"{\color{rulecolor}\leaders\hrule height 0.62ex depth -0.5ex\hfill}"
        body = (rf"{fill}\enspace{title}\enspace{fill}" if centered else rf"{title}\enspace{fill}") + (
            r"\par\vspace{1.2mm}"
        )
    else:
        body = (rf"{{\centering {title}\par}}" if centered else rf"{title}\par") + r"\vspace{1.2mm}"
    return rf"\newcommand{{\resumesection}}[1]{{\par{before}\needspace{{4\baselineskip}}\noindent {body}}}"


def _preamble(doc: ResumeDocument, style: Style, unicode_engine: bool) -> str:
    template = TEMPLATES[doc.template]
    credit = f", inspired by {template['inspired_by']}" if template["inspired_by"] else ""
    pdftex_font, unicode_font = _FONT_SETUP[style.font]
    title = escape(doc.basics.name or "Resume")
    lines = [
        "% !TEX program = lualatex" if unicode_engine else "% !TEX program = pdflatex",
        f"% {doc.basics.name or 'Resume'}: \"{template['label']}\" template{credit}.",
        "% Generated by the Prottoy Resume Builder. Compiles on Overleaf as-is.",
        "% ATS-safe by construction: one column, real text, standard headings,",
        "% no tables or headers/footers, ligatures off, Unicode text mapping on.",
        r"\documentclass[10pt]{article}",
        rf"\usepackage[{style.paper}paper,margin={style.margin:g}mm]{{geometry}}",
        r"\usepackage{iftex}",
        r"\ifPDFTeX",
        r"  \usepackage[T1]{fontenc}",
        r"  \usepackage[utf8]{inputenc}",
        r"  \input{glyphtounicode}",
        r"  \pdfgentounicode=1",
        r"  \pdfinterwordspaceon",  # real space characters, not just gaps
        f"  {pdftex_font}",
        r"  \usepackage{microtype}",
        r"  \DisableLigatures{encoding = *, family = *}",
        r"\else",
        r"  \usepackage{fontspec}",
        r"  \defaultfontfeatures{Ligatures={TeX,NoCommon}}",
        f"  {unicode_font}" if unicode_font else "",
        r"\fi",
        r"\usepackage{xcolor}",
        r"\usepackage{enumitem}",
        r"\usepackage{needspace}",
        r"\usepackage[hidelinks]{hyperref}",
        rf"\hypersetup{{pdftitle={{{title}}},pdfauthor={{{title}}}}}",
        rf"\definecolor{{accent}}{{HTML}}{{{style.accent.lstrip('#').upper()}}}",
        rf"\definecolor{{rulecolor}}{{HTML}}{{{_hex(style.rule_rgb)}}}",
        r"\definecolor{muted}{HTML}{4B5563}",
        r"\definecolor{body}{HTML}{1F2937}",
        r"\pagestyle{empty}",
        r"\setlength{\parindent}{0pt}",
        r"\setlength{\parskip}{0pt}",
        r"\setlist[itemize]{leftmargin=4.5mm,labelsep=2mm,itemsep=0pt,topsep=0pt,parsep=0pt,partopsep=0pt,"
        r"label=\textbullet}",
        _section_macro(style),
        r"\newcommand{\entry}[2]{\par\noindent\textbf{#1}\hfill{\itshape\color{muted}#2}\par}",
        rf"\newcommand{{\metasize}}{{{_size(style.font_size - 0.5, style.line_height * style.font_size / (style.font_size - 0.5))}}}",
    ]
    return "\n".join(line for line in lines if line)


def _body(blocks: list[Block], style: Style) -> list[str]:
    out: list[str] = []
    in_list = False
    centered = style.header_align == "center"
    header: list[str] = []
    previous: Block | None = None

    def close_list():
        nonlocal in_list
        if in_list:
            out.append(r"\end{itemize}")
            in_list = False

    for block in blocks:
        text = escape(block.text)
        if block.kind == "bullet":
            if not in_list:
                out.append(r"\begin{itemize}")
                in_list = True
            out.append(rf"  \item {text}")
            previous = block
            continue
        close_list()

        if block.kind == "name":
            header.append(rf"{{{_size(style.name_size, 1.2)}\bfseries\color{{accent}}{text}\par}}\vspace{{0.6mm}}")
        elif block.kind == "headline":
            header.append(rf"{{{_size(style.font_size + 1.5, style.line_height)}{text}\par}}")
        elif block.kind == "contact":
            items = r" \textbar{} ".join(_contact_item(p) for p in block.parts)
            header.append(rf"{{\metasize\color{{muted}}{items}\par}}")
        else:
            if header:
                out.append(r"\begingroup" + (r"\centering" if centered else r"\raggedright"))
                out.extend(header)
                out.append(r"\endgroup")
                header = []
            if block.kind == "heading":
                title = block.text.title() if style.heading_case == "smallcaps" else text
                out.append(rf"\resumesection{{{escape(title)}}}")
            elif block.kind == "entry_title":
                if previous is not None and previous.kind != "heading":
                    out.append(r"\vspace{1.2mm}")
                out.append(rf"\entry{{{text}}}{{{escape(block.aside)}}}")
            elif block.kind == "entry_meta":
                out.append(rf"{{\metasize\itshape\color{{muted}}{text}\par}}")
            elif block.kind == "skill":
                rest = escape(block.text[len(block.label) + 1:].strip())
                # A word space after a bold run in a tight face (Source Sans) is
                # narrower than extractors' word gap, so "Languages:Python";
                # an en-space is wide enough everywhere.
                out.append(rf"\textbf{{{escape(block.label)}:}}\enspace {rest}\par")
            else:
                out.append(rf"{text}\par")
        previous = block
    close_list()
    if header:
        out.append(r"\begingroup" + (r"\centering" if centered else r"\raggedright"))
        out.extend(header)
        out.append(r"\endgroup")
    return out


def render_latex(doc: ResumeDocument) -> bytes:
    style = resolve_style(doc)
    blocks = build_blocks(doc, style)
    unicode_engine = not all(_PDFTEX_SAFE.match(b.text + b.aside) for b in blocks)
    parts = [
        _preamble(doc, style, unicode_engine),
        r"\begin{document}",
        r"\raggedright",
        rf"{_size(style.font_size, style.line_height)}\color{{body}}",
        *_body(blocks, style),
        r"\end{document}",
        "",
    ]
    return "\n".join(parts).encode("utf-8")
